title: Yunkyeong Kang
logo: /assets/img/KAIST_startup_cropped.jpeg
description: >
  <strong style="font-size:1.1em;">Bioengineering Researcher</strong><br>
  <span style="color:gray;">M.S. student @KAIST</span>
# description: M.S. student at KAIST, Graduate School of Engineering Department. Interested in bioinformatics and computational biology.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
cv: https://tinykrex.github.io/assets/cv/cv_riveryk.pdf
cv_kor: https://tinykrex.github.io/assets/cv/cv_riveryk_kor.pdf
# gs: # google scholar address
email: riveryk@kaist.ac.kr
